### ISSUE TITLE
Should respond with 204 No Content

### ISSUE THREAD

**Issue by mrazzari** [thegillis/blank_pixel#1]
See http://www.phpied.com/204-no-content/
No reason not to.

**Comment by thegillis** [comment]
Well, in this case there was a reason.

We were using a CDN that had issues passing along requests that responded with a no content header. This particular solution allowed us to still use this CDN and pass along the requests to the origin.

This was also more of an attempt to explore how to write a GEM in the first place and really needs to be modified if it continues to exist, possibly transforming into a "responder", etc.
